import React, { useEffect, useState } from 'react';
import { Textarea } from './Textarea';
import ZuboraWorker from 'worker-loader?name=static/[hash].worker.js!../workers/zubora.worker';

let worker;
const ZuboraApp: React.FC = (): React.ReactElement => {
  const placeholderTS = `function greeter(person: string) {
  return "Hello, " + person;
}
export { greeter }
`;
  /** Result */
  const [zuboraResult, setZuboraResult] = useState('');

  /** Zubora worker */
  useEffect(() => {
    worker = new ZuboraWorker();
    return () => worker.terminate();
  }, []);
  function onMessage({ data }): void {
    setZuboraResult(data);
  }
  function handleOnChange(e: React.ChangeEvent<HTMLTextAreaElement>) {
    worker.onmessage = onMessage;
    worker.postMessage(e.target.value);
  }

  return (
    <div className="grid grid-rows-1 grid-cols-2 gap-2 mx-2 md-1">
      <div>
        <p>Input your JS/TS module code here:</p>
        <Textarea
          placeholder={placeholderTS}
          handleOnChange={handleOnChange}
          value={placeholderTS}
        ></Textarea>
      </div>
      <div>
        <p>Test template generated by zubora:</p>
        <Textarea value={zuboraResult} disabled={true}></Textarea>
      </div>
    </div>
  );
};
export { ZuboraApp };
