import React, { useEffect, useState } from 'react';
import AceEditor from 'react-ace';
require('ace-builds/src-noconflict/mode-json');
require('ace-builds/src-noconflict/mode-typescript');
require('ace-builds/src-noconflict/snippets/json');
require('ace-builds/src-noconflict/snippets/typescript');
require('ace-builds/src-noconflict/theme-github');
import ZuboraWorker from 'worker-loader?name=static/[hash].worker.js!../workers/zubora.worker';

let worker;
const ZuboraApp: React.FC = (): React.ReactElement => {
  const placeholderTS = `function greeter(person: string) {
  return "Hello, " + person;
}
export { greeter }
`;
  /** Result */
  const [zuboraResult, setZuboraResult] = useState('');

  /** Zubora worker */
  useEffect(() => {
    if (!worker) {
      worker = new ZuboraWorker();
    }
    return () => worker.terminate();
  }, []);
  function onMessage({ data }): void {
    setZuboraResult(data);
  }
  function invokeWorker(value: string) {
    if (!worker) {
      worker = new ZuboraWorker();
    }
    worker.onmessage = onMessage;
    worker.postMessage(value);
  }
  function aceOnChange(value: string) {
    invokeWorker(value);
  }
  function aceOnLoad() {
    invokeWorker(placeholderTS);
  }

  return (
    <div className="grid grid-rows-1 grid-cols-2 gap-2 md-1">
      <div>
        <h2>Input your JS/TS module code here:</h2>
        <AceEditor
          height={'calc(100vh - 100px)'}
          width={'calc(50vw - 2px)'}
          theme="github"
          fontSize={14}
          showPrintMargin={true}
          showGutter={true}
          highlightActiveLine={true}
          setOptions={{
            enableBasicAutocompletion: false,
            enableLiveAutocompletion: false,
            enableSnippets: false,
            showLineNumbers: true,
            tabSize: 2,
          }}
          placeholder="Input your JS / TS module code here."
          mode="typescript"
          value={placeholderTS}
          onLoad={aceOnLoad}
          onChange={aceOnChange}
        />
      </div>
      <div>
        <h2>Test template generated by zubora:</h2>
        <AceEditor
          height={'calc(100vh - 100px)'}
          width={'calc(50vw - 2px)'}
          theme="github"
          fontSize={14}
          showPrintMargin={true}
          showGutter={true}
          highlightActiveLine={true}
          setOptions={{
            enableBasicAutocompletion: false,
            enableLiveAutocompletion: false,
            enableSnippets: false,
            showLineNumbers: true,
            tabSize: 2,
          }}
          placeholder="Zubora Result will appear here."
          mode={typeof zuboraResult === 'string' ? 'typescript' : 'json'}
          value={
            typeof zuboraResult === 'string'
              ? zuboraResult
              : JSON.stringify(zuboraResult)
          }
          readOnly={true}
        />
      </div>
      <style jsx>{``}</style>
    </div>
  );
};
export { ZuboraApp };
