import React, { useEffect, useContext } from 'react';
import { observer } from 'mobx-react-lite';
import { ZuboraStoreContext } from '../store/ZuboraStore';

import AceEditor from 'react-ace';
require('ace-builds/src-noconflict/mode-json');
require('ace-builds/src-noconflict/mode-typescript');
require('ace-builds/src-noconflict/snippets/json');
require('ace-builds/src-noconflict/snippets/typescript');
require('ace-builds/src-noconflict/theme-github');
import ZuboraWorker from 'worker-loader?name=static/[hash].worker.js!../workers/zubora.worker';

let worker;
const ZuboraApp: React.FC = observer(
  (): React.ReactElement => {
    const initialCode = `function greeter(person: string) {
  return "Hello, " + person;
}
export { greeter }
`;
    const zuboraStore = useContext(ZuboraStoreContext);

    /** Zubora worker */
    useEffect(() => {
      if (!worker) {
        worker = new ZuboraWorker();
      }
      return () => worker.terminate();
    }, []);
    function onMessage({ data }): void {
      zuboraStore.result = data;
    }
    function invokeWorker(value: string) {
      if (!worker) {
        worker = new ZuboraWorker();
      }
      worker.onmessage = onMessage;
      zuboraStore.code = value;
      worker.postMessage(value);
    }
    function aceOnChange(value: string) {
      invokeWorker(value);
    }
    function aceOnLoad() {
      zuboraStore.code = initialCode;
      invokeWorker(initialCode);
    }

    return (
      <div className="grid grid-rows-1 grid-cols-2 gap-2 md-1">
        <div>
          <h2>Input your JS/TS module code here:</h2>
          <AceEditor
            height={'calc(100vh - 100px)'}
            width={'calc(50vw - 2px)'}
            theme="github"
            fontSize={14}
            showPrintMargin={true}
            showGutter={true}
            highlightActiveLine={true}
            setOptions={{
              enableBasicAutocompletion: false,
              enableLiveAutocompletion: false,
              enableSnippets: false,
              showLineNumbers: true,
              tabSize: 2,
            }}
            placeholder="Input your JS / TS module code here."
            mode="typescript"
            value={zuboraStore.code}
            onLoad={aceOnLoad}
            onChange={aceOnChange}
          />
        </div>
        <div>
          <h2>Test template generated by zubora:</h2>
          <AceEditor
            height={'calc(100vh - 100px)'}
            width={'calc(50vw - 2px)'}
            theme="github"
            fontSize={14}
            showPrintMargin={true}
            showGutter={true}
            highlightActiveLine={true}
            setOptions={{
              enableBasicAutocompletion: false,
              enableLiveAutocompletion: false,
              enableSnippets: false,
              showLineNumbers: true,
              tabSize: 2,
            }}
            placeholder="Zubora Result will appear here."
            mode={
              typeof zuboraStore.result === 'string' ? 'typescript' : 'json'
            }
            value={
              typeof zuboraStore.result === 'string'
                ? zuboraStore.result
                : JSON.stringify(zuboraStore.result)
            }
            readOnly={true}
          />
        </div>
        <style jsx>{``}</style>
      </div>
    );
  }
);
export { ZuboraApp };
